site_name: 起動環境作成ガイド 

pages:
- Home: index.md
- PE Builder: builderPE.md
- Linux Builder: builderLinux.md

markdown_extensions:
 - toc:
    baselevel: 2

site_favicon: favicon.ico

theme: readthedocs
